x-service-defaults: &defaults
  build:
    context: .
    dockerfile: Dockerfile
  restart: unless-stopped

services:
  vancouver:
    <<: *defaults
    container_name: polargrid-vancouver
    ports:
      - "8001:8000"
    env_file: configs/vancouver.env

  toronto:
    <<: *defaults
    container_name: polargrid-toronto
    ports:
      - "8002:8000"
    env_file: configs/toronto.env

  london:
    <<: *defaults
    container_name: polargrid-london
    ports:
      - "8003:8000"
    env_file: configs/london.env

  frankfurt:
    <<: *defaults
    container_name: polargrid-frankfurt
    ports:
      - "8004:8000"
    env_file: configs/frankfurt.env

  singapore:
    <<: *defaults
    container_name: polargrid-singapore
    ports:
      - "8005:8000"
    env_file: configs/singapore.env
